name: Generate Customized Pac-Man Game

on:
  schedule:
    - cron: "0 0 * * *"        # daily at midnight UTC
  workflow_dispatch:           # manual trigger
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate pacman-contribution-graph.svg with custom colors
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          # Example custom colors: change these to your preference
          color_pacman: "#FFEB3B"                # bright yellow Pac-Man
          color_dots: "#FFCC80,#FFB74D,#FF9800,#F57C00" # orange shades for dots
          color_ghosts: "#E91E63,#9C27B0,#2196F3,#4CAF50" # pink, purple, blue, green ghosts
          # Add more inputs if available for animation speed, background, etc.

      - name: Prepare output folder
        run: |
          mkdir -p dist
          mv pacman-contribution-graph.svg dist/
          # If dark theme SVG generated, move it too (adjust name as needed)
          # mv pacman-contribution-graph-dark.svg dist/

      - name: List files for debugging
        run: ls -R dist

      - name: Push pacman SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
