name: Generate Customized Pac-Man Game

on:
  schedule:
    - cron: "0 0 * * *"        # daily at midnight UTC
  workflow_dispatch:           # manual trigger
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate pacman-contribution-graph.svg with custom colors
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          color_pacman: "#FFEB3B"
          color_dots: "#F57C00"
          color_ghosts: "#1976D2"

      - name: Prepare output folder
        run: |
          mkdir -p dist
         if [ -f pacman-contribution-graph.svg ]; then
            mv pacman-contribution-graph.svg dist/
          fi
          if [ -f pacman-contribution-graph-dark.svg ]; then
            mv pacman-contribution-graph-dark.svg dist/
          fi
      - name: List files for debugging
        run: ls -R dist

      - name: Push pacman SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
